/** Provides functionality for inferring types. */

/*
 * Known limitations:
 * - Implicit constructors in classes and structs are not generated by the extractor
 * - Pattern matching, including enum destructuring
 * - Inferred qualifiers `.foo`
 * - Type parameter bounds (`foo<T : Protocol>(x : T)`)
 * - Type parameter constraints (`foo<T>(x : T) where T: Protocol`); are currently not extracted
 * - Associated types on type parameters, e.g. `func foo<T : Protocol>(x : T) -> T.AssociatedType`
 * - `Self` inside protocol extensions
 * - Type parameters inherited in extensions (extractor change?)
 * - Primary associated types
 * - Key paths
 * - Overloading (both arity based and type based)
 * - Indexing expressions
 * - Operations
 * - Inherited constructors
 * - Closure short-hand parameters `$0`, `$1`, etc (extractor change?)
 */

private import codeql.util.Unit
private import codeql.typeinference.internal.TypeInference
private import codeql.unified.internal.CallableEx
private import codeql.unified.internal.ExprPositions
private import codeql.unified.internal.NameBinding
private import utils.test.InlineExpectationsTest
private import Type
private import Type as T
private import TypeAbstraction
private import TypeAbstraction as TA
private import TypeMention
private import TypeInferencePlugin
private import TypeInferencePlugin as Plugin

class Type = T::Type;

private module Input1 implements InputSig1<Location> {
  private import Type as T

  class Type = T::Type;

  class PseudoType = T::PseudoType;

  class TypeParameter = T::TypeParameter;

  class TypeAbstraction = TA::TypeAbstraction;

  int getTypeParameterId(TypeParameter tp) {
    CachedStage::ref() and
    tp =
      rank[result](TypeParameter tp0, int kind, int id1, int id2 |
        kind = 1 and
        id1 = idOfTypeParameterAstNode(tp0.(TypeParameterType).getTypeParameter()) and
        id2 = 0
        or
        kind = 2 and
        exists(ClassLikeDeclaration c, AssociatedTypeDeclaration a |
          tp0 = TAssociatedTypeParameterType(c, a, _) and
          id1 = idOfTypeParameterAstNode(c) and
          id2 = idOfTypeParameterAstNode(a)
        )
        or
        kind = 3 and
        tp0 = TUnknownTypeTypeParameter(id1) and
        id2 = 0
      |
        tp0 order by kind, id1, id2
      )
  }
}

private import Input1

private module M1 = Make1<Location, Input1>;

import M1

predicate getTypePathLimit = Input1::getTypePathLimit/0;

predicate getTypeParameterId = Input1::getTypeParameterId/1;

class TypePath = M1::TypePath;

module TypePath = M1::TypePath;

private module Input2 implements InputSig2<TypeMention> {
  TypeMention getATypeParameterConstraint(TypeParameter tp) {
    result = tp.(TypeParameterType).getTypeParameter().getBound()
  }

  predicate conditionSatisfiesConstraint(
    TypeAbstraction abs, TypeMention condition, TypeMention constraint, boolean transitive
  ) {
    transitive = true and
    abs =
      any(ClassLikeDeclaration c |
        condition = getClassLikeDeclarationTypeMention(c) and
        constraint = c.getABaseType().getType()
      )
  }

  predicate typeParameterIsFunctionallyDetermined(TypeParameter tp) {
    tp instanceof AssociatedTypeParameterType
  }

  predicate typeAbstractionHasAmbiguousConstraintAt(
    TypeAbstraction abs, Type constraint, TypePath path
  ) {
    none() // todo
  }
}

private import Input2

private module M2 = Make2<TypeMention, Input2>;

import M2

private module Input3 implements InputSig3 {
  private import unified as Unified

  predicate cacheRevRef() {
    (exists(resolveFieldAccess(_)) implies any())
    or
    (exists(resolveCallTarget(_)) implies any())
  }

  predicate inferTypeForDefaults = M3::inferType/2;

  class UnknownType = T::UnknownType;

  class BoolType = Plugin::BoolType;

  class AstNode = Unified::AstNode;

  class Expr extends Unified::Expr {
    Expr() { isInAssignmentContext(this, _) or hasResultValue(this) }
  }

  class Cast extends Expr, TypeCastExpr {
    TypeMention getType() { result = TypeCastExpr.super.getType() }
  }

  class Switch extends Expr, SwitchExpr {
    Expr getExpr() { result = super.getValue() }

    Case getCase(int index) { result = super.getCase(index) }
  }

  class Case extends SwitchCase {
    AstNode getAPattern() { result = super.getPattern() }

    AstNode getBody() { result = super.getBody() }
  }

  class ConditionalExpr extends Expr instanceof IfExpr {
    Expr getCondition() { result = super.getCondition() }

    Expr getThen() { result = super.getThen() }

    Expr getElse() { result = super.getElse() }
  }

  class BinaryExpr extends Expr, Unified::BinaryExpr {
    Expr getLeftOperand() { result = super.getLeft() }

    Expr getRightOperand() { result = super.getRight() }
  }

  class LogicalAndExpr extends BinaryExpr, Unified::LogicalAndExpr { }

  class LogicalOrExpr extends BinaryExpr, Unified::LogicalOrExpr { }

  class Assignment extends BinaryExpr, Unified::Assignment { }

  class AssignExpr extends Assignment, Unified::AssignExpr { }

  class ParenExpr extends Expr {
    ParenExpr() { none() }

    Expr getExpr() { none() }
  }

  private newtype TDeclaration =
    TAstVariableDeclaration(Unified::VariableDeclaration decl) or
    TCallableExDeclaration(CallableEx c) or
    TParameterExDeclaration(ParameterEx p)

  final class Declaration = DeclarationImpl;

  abstract private class DeclarationImpl extends TDeclaration {
    abstract TypeMention getDeclaringType();

    abstract TypeMention getType();

    abstract Identifier getNameNode();

    abstract string toString();

    abstract Location getLocation();

    pragma[nomagic]
    predicate isMemberOf(ClassLikeDeclaration cls, Identifier i, string name) {
      exists(NamespaceNode ns |
        ns.isInstanceMemberNamespace(cls) and
        ns.getMember(name).isIdentifier(i) and
        i = this.getNameNode()
      )
    }

    CallableEx asCallableEx() { this = TCallableExDeclaration(result) } // todo: remove?
  }

  class Variable extends LocalNameBindingOutput::Local {
    Expr getAnAccess() { result = super.getAnAccess() }
  }

  final class VariableDeclaration = VariableDeclarationImpl;

  abstract private class VariableDeclarationImpl extends DeclarationImpl {
    abstract AstNode getPattern();

    abstract AstNode getInitializer();

    predicate preservesInitializerType() { any() }
  }

  private class AstVariableDeclaration extends VariableDeclarationImpl, TAstVariableDeclaration {
    Unified::VariableDeclaration decl;

    AstVariableDeclaration() { this = TAstVariableDeclaration(decl) }

    Unified::VariableDeclaration getDecl() { result = decl }

    override TypeMention getDeclaringType() { none() }

    override TypeMention getType() { result = decl.getType() }

    override Identifier getNameNode() { result = decl.getPattern() }

    override AstNode getPattern() { result = decl.getPattern() }

    override AstNode getInitializer() { result = decl.getValue() }

    override string toString() { result = decl.toString() }

    override Location getLocation() { result = decl.getLocation() }
  }

  class Field extends AstVariableDeclaration {
    ClassLikeDeclaration cls;

    Field() { decl = cls.getAMember() }

    override TypeMention getDeclaringType() { result = getClassLikeDeclarationTypeMention(cls) }
  }

  private class EnumField_ extends Field {
    override EnumField decl;

    override TypeMention getType() { result = decl.getEnum().getNameNode() }
  }

  abstract class FieldAccess extends Expr {
    abstract Expr getReceiver();

    abstract Field getField();
  }

  pragma[nomagic]
  private predicate lookupMember0(MemberAccessExpr mae, ClassLikeDeclaration cls, string name) {
    cls = inferType(mae.getBase()).(ClassLikeDeclarationType).getClassLikeDeclaration() and
    name = mae.getMemberName()
  }

  pragma[nomagic]
  private Declaration lookupMember(MemberAccessExpr mae) {
    exists(ClassLikeDeclaration cls, string name | lookupMember0(mae, cls, name) |
      result.isMemberOf(cls, _, name)
      or
      exists(CallableEx ctor |
        ctor = result.asCallableEx() and
        ctor.isConstructor(cls) and
        name = ctor.getName()
      )
    )
  }

  private class MemberAccessExprFieldAccess extends FieldAccess, MemberAccessExpr {
    override Expr getReceiver() { result = this.getBase() }

    pragma[nomagic]
    private predicate isTupleProjection(TupleType tuple, string name) {
      tuple = inferType(this.getBase()) and
      name = this.getMemberName()
    }

    override Field getField() {
      // mutual recursion; resolving qualified fields requires resolving types and vice versa
      result = lookupMember(this)
      or
      // also mutual recursion
      exists(TupleType tuple, string name |
        this.isTupleProjection(tuple, name) and
        result.getDecl() = tuple.getField(name)
      )
      or
      // no mutual recursion; can be resolved directly with static name binding
      result.getNameNode() = getStaticBindingTargetFromRef(this)
    }
  }

  private Type getImplicitReceiverType(UnqualifiedMemberAccess uma, TypePath path) {
    exists(Parameter p, Unified::Callable c |
      p.getParameterEx().isImplicitReceiverParameter(c) and
      c = uma.getImplicitQualifierVariable().getDeclaringCallable() and
      result = p.getType().getTypeAt(path)
    )
  }

  private class UnqualifiedMemberAccessFieldAccess extends FieldAccess, UnqualifiedMemberAccess {
    override Expr getReceiver() { none() }

    override Field getField() { result.getNameNode() = this.getTarget() }
  }

  Type inferFieldAccessReceiverType(FieldAccess fa, TypePath path) {
    // instance field with explicit receiver
    result = inferType(fa.getReceiver(), path)
    or
    // static field with type qualifier
    result = fa.(MemberAccessExpr).getBase().(TypeMention).getTypeAt(path)
    or
    // field with implicit receiver
    result = getImplicitReceiverType(fa, path)
  }

  Type inferFieldAccessReceiverTypeContextual(Expr receiver, TypePath path) {
    result = M3::inferFieldAccessReceiverTypeContextualDefault(_, receiver, path)
  }

  class Return extends ReturnExpr {
    Expr getExpr() { result = this.getValue() }
  }

  class Parameter extends VariableDeclarationImpl, TParameterExDeclaration {
    ParameterEx p;

    Parameter() { this = TParameterExDeclaration(p) }

    ParameterEx getParameterEx() { result = p }

    override AstNode getPattern() { result = p.asParameter().getPattern() }

    override AstNode getInitializer() { none() }

    override TypeMention getDeclaringType() { none() }

    override TypeMention getType() {
      result = p.asParameter().getType()
      or
      // todo: cleanup
      exists(Unified::Callable c |
        p.isImplicitReceiverParameter(c) and
        exists(ClassLikeDeclaration encl |
          result = getClassLikeDeclarationTypeMention(encl) and
          c = encl.getAMember()
        )
      )
      or
      // todo: cleanup and account for type specialization
      exists(ClassLikeDeclaration cls, string name | p.isDefaultConstructorParameter(cls, _, name) |
        exists(Field f |
          f.isMemberOf(cls, _, name) and
          result = f.getType()
        )
        or
        name = "self" and
        result = getClassLikeDeclarationTypeMention(cls)
      )
    }

    override Identifier getNameNode() { none() }

    override string toString() { result = p.toString() }

    override Location getLocation() { result = p.getLocation() }
  }

  predicate implicitParameterDecl(Parameter p, Variable v) {
    exists(Unified::Callable c |
      p.getParameterEx().isImplicitReceiverParameter(c) and // todo
      v.(LocalVariable).isImplicitReceiverParameter(c)
    )
  }

  class Callable extends DeclarationImpl, TCallableExDeclaration {
    CallableEx c;

    Callable() { this = TCallableExDeclaration(c) }

    CallableEx getCallableEx() { result = c }

    override TypeMention getDeclaringType() {
      result = c.asCallable().(EnumConstructor).getEnum().getNameNode()
      or
      not c.asCallable() instanceof EnumConstructor and
      exists(ClassLikeDeclaration cls |
        c.isMemberOf(cls) and
        result = getClassLikeDeclarationTypeMention(cls)
      )
    }

    override TypeMention getType() {
      result = c.getReturnType()
      or
      c.isConstructor(_) and
      result = this.getDeclaringType()
    }

    override Identifier getNameNode() { result = c.getNameNode() }

    TypeParameter getTypeParameter(int i) { result = TTypeParameterType(c.getTypeParameter(i)) }

    TypeMention getAdditionalTypeParameterConstraint(TypeParameter tp) {
      // todo: type equalities?
      exists(BoundTypeConstraint constraint |
        constraint = c.asCallable().(FunctionDeclaration).getATypeConstraint() and
        tp = constraint.getType().(TypeMention).getType() and
        result = constraint.getBound()
      )
    }

    Parameter getParameter(int i) { result.getParameterEx() = c.getParameter(i) }

    AstNode getBody() { result = c.getBody() }

    override string toString() { result = c.toString() }

    override Location getLocation() { result = c.getLocation() }
  }

  Callable getEnclosingCallable(AstNode node) {
    result.getCallableEx().asCallable() = node.getEnclosingCallable()
  }

  class InvocationResolutionContext = Unit;

  class Invocation extends Expr, CallExpr {
    Type getTypeQualifier(TypePath path) {
      exists(TypeMention tm | result = tm.getTypeAt(path) |
        tm = super.getCallee()
        or
        not super.getCallee() instanceof TypeMention and
        tm = super.getCallee().(MemberAccessExpr).getBase()
      )
    }

    Type getTypeArgument(int i, TypePath path) { none() }

    int getNumberOfArguments() { result = CallExpr.super.getNumberOfArguments() + 1 }

    Expr getArgument(int i) {
      i = 0 and
      exists(boolean isFunctionExprInvoke | exists(this.getTargetImpl(isFunctionExprInvoke)) |
        if isFunctionExprInvoke = true
        then result = CallExpr.super.getCallee()
        else result = CallExpr.super.getCallee().(MemberAccessExpr).getBase()
      )
      or
      result = CallExpr.super.getArgument(i - 1).getValue()
    }

    /** Gets the special `invoke` target when the callee evaluates to a function expression. */
    pragma[nomagic]
    Unified::Callable getInvokeTarget(Type t) {
      t = inferType(this.getCallee()) and
      result = getFunctionInvoke(t)
    }

    private CallableEx getTargetViaStaticNameBinding() {
      exists(NameBinding b | b = getStaticBindingTargetFromRef(this.getCallee()) |
        // object creation (including enum constructors): `String(42)`, `Optional.Some(42)`
        exists(ClassLikeDeclaration cls |
          cls.getNameNode() = b and
          result.isConstructor(cls)
        )
        or
        // call without explicit receiver: `foo(42)`
        result.getNameNode() = b
      )
    }

    CallableEx getTargetImpl(boolean isFunctionExprInvoke) {
      // mutual recursion; call with explicit receiver: `obj.foo(42)`
      result = lookupMember(this.getCallee()).asCallableEx() and
      isFunctionExprInvoke = false
      or
      // mutual recursion; call to a function expression: `callback(42)`
      result.asCallable() = this.getInvokeTarget(_) and
      isFunctionExprInvoke = true
      or
      // no mutual recursion; can be resolved directly with static name binding
      result = this.getTargetViaStaticNameBinding() and
      isFunctionExprInvoke = false
    }

    Callable getTarget(InvocationResolutionContext c) {
      result.asCallableEx() = this.getTargetImpl(_) and
      exists(c)
    }

    Callable getATargetForTypeQualifierMatching() {
      result.asCallableEx() = this.getTargetViaStaticNameBinding()
    }
  }

  Type inferInvocationArgumentType(
    Invocation invocation, InvocationResolutionContext ctx, int i, TypePath path
  ) {
    exists(ctx) and
    (
      // A call to a function expression
      exists(Type t | exists(invocation.getInvokeTarget(t)) |
        i = 0 and
        result = inferType(invocation.(CallExpr).getCallee(), path)
        or
        exists(TypePath prefix, TypePath suffix, int j |
          functionInvokeSignature(t, invocation.getNumberOfArguments() - 1, j, i, prefix) and
          result = inferType(invocation.getArgument(j + 1), suffix) and
          path = prefix.append(suffix)
        )
      )
      or
      // A call to a regular function or method
      exists(invocation.getTargetImpl(false)) and
      (
        result = inferType(invocation.getArgument(i), path)
        or
        i = 0 and
        result = getImplicitReceiverType(invocation.(CallExpr).getCallee(), path)
      )
    )
  }

  Type inferInvocationArgumentTypeContextual(Expr arg, TypePath path) {
    result = M3::inferInvocationArgumentTypeContextualDefault(_, _, _, arg, path)
  }

  Type inferInvocationType(Invocation invocation, TypePath path) {
    result = M3::inferInvocationTypeDefault(invocation, _, path)
  }

  class Closure extends Callable {
    private FunctionExpr fe;

    Closure() { fe = this.getCallableEx().asCallable() }

    Expr getDefiningExpr() { result = fe }
  }

  class ClosureParameterPseudoType extends T::ClosureParameterPseudoType {
    Parameter getParameter() { result.getParameterEx().asParameter() = this.getParam() }
  }

  pragma[nomagic]
  Type getClosureType(Closure c) { result = getFunctionExprType(c.getDefiningExpr()) }

  pragma[nomagic]
  TypePath getClosureParameterTypePath(Parameter p) {
    exists(FunctionExpr fe, Type t, int i |
      p.getParameterEx().asParameter() = fe.getParameter(i) and
      t = getFunctionExprType(fe) and
      result = getFunctionExprParameterTypePath(t, fe.getNumberOfParameters(), i)
    )
  }

  pragma[nomagic]
  TypePath getClosureReturnTypePath(Closure c) {
    result = getFunctionExprReturnTypePath(getClosureType(c))
  }

  predicate stepLanguageSpecific(AstNode n1, TypePath prefix1, AstNode n2, TypePath prefix2) {
    n1 = n2.(Block).getLastStmt() and
    prefix1.isEmpty() and
    prefix2.isEmpty()
    or
    hasResultValue(n2) and
    n1 = n2.(ArrayLiteral).getAnElement() and
    prefix1.isEmpty() and
    prefix2 = TypePath::singleton(getArrayElementTypeParameter())
    or
    hasResultValue(n2) and
    n2 =
      any(TupleExpr te |
        exists(int i, int arity, TupleType tt |
          n1 = te.getElement(i).getValue() and
          arity = te.getNumberOfElements() and
          tt.getArity() = arity and
          prefix1.isEmpty() and
          prefix2 = TypePath::singleton(tt.getPositionalTypeParameter(i))
        )
      )
  }

  Type inferTypeLanguageSpecific(AstNode n, TypePath path) {
    result = Plugin::inferType(n, path)
    or
    n instanceof BooleanLiteral and
    result instanceof BoolType and
    path.isEmpty()
    or
    n instanceof IntLiteral and
    result instanceof IntType and
    path.isEmpty()
    or
    n instanceof FloatLiteral and
    result instanceof FloatType and
    path.isEmpty()
    or
    n instanceof StringLiteral and
    result instanceof StringType and
    path.isEmpty()
    or
    exists(ClassLikeDeclaration c |
      c = n.(SuperExpr).getEnclosingClass() and
      result = c.getBaseType(0).getType().(TypeMention).getTypeAt(path)
    )
    or
    // `Optional.none` has an unknown `Wrapper` type
    exists(EnumField_ f, TypeParameter tp |
      n.(FieldAccess).getField() = f and
      tp = f.getType().getType().getATypeParameter() and
      path = TypePath::singleton(tp) and
      // `Optional<String>.none` does not have an unknown `Wrapper` type
      not exists(n.(MemberAccessExpr).getBase().(TypeMention).getTypeAt(path))
    ) and
    result instanceof UnknownType
  }

  pragma[nomagic]
  Type inferTypeCertainLanguageSpecific(AstNode n, TypePath path) { none() }
}

private module M3 = Make3<Input3>;

predicate inferType = M3::inferType/1;

predicate inferType = M3::inferType/2;

predicate inferTypeCertain = M3::inferTypeCertain/2;

module Consistency = M3::Consistency;

module CachedStage = M3::CachedStage;

/**
 * Gets the field that is accessed by the given expression.
 *
 * `access` is either a `MemberAccessExpr` or an `Identifier` (when
 * the field is accessed with an implicit receiver).
 */
cached
VariableDeclaration resolveFieldAccess(Expr access) {
  CachedStage::ref() and
  result = access.(Input3::FieldAccess).getField().getDecl()
}

/**
 * Gets the static call target of the given call expression.
 *
 * Does not yet take overloading into account.
 */
cached
CallableEx resolveCallTarget(CallExpr ce) {
  CachedStage::ref() and
  result = ce.(Input3::Invocation).getTargetImpl(_)
}

private predicate typeTestAstNodeRepr(AstNode n, string repr) {
  repr = [n.toString(), n.(Identifier).getValue(), "." + n.(MemberAccessExpr).getMemberName()]
}

module TypeTest implements TestSig {
  private module M = M3::TypeTest<typeTestAstNodeRepr/2>;

  import M

  predicate hasOptionalResult = M::hasOptionalResult/4;
}

/** Provides predicates for debugging the type inference implementation. */
private module Debug {
  AstNode getRelevantNode() {
    exists(string filepath, int startline, int startcolumn, int endline, int endcolumn |
      result.getLocation().hasLocationInfo(filepath, startline, startcolumn, endline, endcolumn) and
      filepath.matches("%/test.swift") and
      startline = 1
    )
  }

  Type debugInferType(AstNode n, TypePath path) {
    n = getRelevantNode() and
    result = inferType(n, path)
  }

  CallableEx debugResolveCallTarget(CallExpr ce) {
    ce = getRelevantNode() and
    result = resolveCallTarget(ce)
  }

  predicate debugTypeMention(TypeMention tm, TypePath path, Type type) {
    tm = getRelevantNode() and
    tm.getTypeAt(path) = type
  }

  predicate atLimit = M3::Debug::atLimit/1;

  predicate inferTypeForNodeAtLimit = M3::Debug::inferTypeForNodeAtLimit/2;

  predicate countTypesForNodeAtLimit = M3::Debug::countTypesForNodeAtLimit/2;

  predicate maxTypes = M3::Debug::maxTypes/4;

  predicate maxTypePath = M3::Debug::maxTypePath/4;

  predicate maxTypePaths = M3::Debug::maxTypePaths/4;

  Type debugInferTypeCertain(AstNode n, TypePath path) {
    n = getRelevantNode() and
    result = inferTypeCertain(n, path)
  }

  Type debugInferCertainNonUniqueType(AstNode n, TypePath path) {
    n = getRelevantNode() and
    Consistency::nonUniqueCertainType(n, path) and
    result = inferTypeCertain(n, path)
  }
}
